import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    marginHorizontal: 16,
    padding: 16,
    gap: 12,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  icon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#EEF1FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTexts: { flex: 1 },
  title: { fontSize: 15, fontWeight: '700', color: '#1A1A2E' },
  subtitle: { fontSize: 12, color: '#888', marginTop: 2 },
  hint: { fontSize: 12, color: '#888', lineHeight: 17 },
  warning: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFF4E5',
    borderRadius: 10,
    padding: 10,
  },
  warningText: { flex: 1, fontSize: 12, color: '#B26A00', lineHeight: 16 },
  input: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#1A1A2E',
    backgroundColor: '#F8F9FA',
  },
  primaryBtn: {
    backgroundColor: '#4A6CF7',
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: 'center',
  },
  primaryBtnDisabled: { opacity: 0.5 },
  primaryBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  actionsRow: { flexDirection: 'row', gap: 10 },
  secondaryBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#4A6CF7',
  },
  secondaryBtnText: { color: '#4A6CF7', fontSize: 14, fontWeight: '700' },
  dangerBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FF4444',
  },
  dangerBtnText: { color: '#FF4444', fontSize: 14, fontWeight: '700' },
  alertRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  alertName: { flex: 1, fontSize: 13, color: '#1A1A2E' },
});
